APP_NAME = "blog"
DEBUG = False
SECRET_KEY = "development-only-change-me"
DATABASE_URL = None

SERVER_HOST = "127.0.0.1"
SERVER_PORT = 8000
SERVER_WORKERS = 1
SERVER_RELOAD = False

PUBLIC_URL = "/public"
PUBLIC_DIRECTORY = "public"
PUBLIC_CACHE_SECONDS = 86400

TASK_QUEUE_URL = "postgres://postgres@localhost/blog_tasks"
TASK_CONCURRENCY = 10
TASK_DEFAULT_RETRIES = 3
TASK_DEFAULT_TIMEOUT = 60
TASKS_INLINE = False

CHANNEL_URL = TASK_QUEUE_URL
CHANNEL_PATH = "/channels"
CHANNEL_ALLOWED_ORIGINS = []
CHANNEL_BUFFER_SIZE = 100
CHANNEL_MAX_MESSAGE_BYTES = 65536
